# Generated by Django 4.2.1 on 2024-02-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0002_alter_user_carrinho_de_compras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='carrinho_de_compras',
        ),
        migrations.AddField(
            model_name='carrinhodecompras',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EcommerceProject.user'),
            preserve_default=False,
        ),
    ]
