# Generated by Django 4.2.1 on 2024-02-08 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0003_remove_user_carrinho_de_compras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhodecompras',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceProject.user'),
        ),
    ]
