# Generated by Django 4.2.1 on 2024-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0005_user_nome_sobrenome_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
