# Generated by Django 4.2.1 on 2024-02-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0007_alter_user_email_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='senha',
            field=models.CharField(default=123432, max_length=40),
            preserve_default=False,
        ),
    ]
