# Generated by Django 4.2.1 on 2024-02-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0008_user_senha'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='nome_sobrenome_unico',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
