# Generated by Django 4.2.1 on 2024-02-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0010_categoria_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Categoria',
            field=models.ManyToManyField(to='EcommerceProject.categoria'),
        ),
    ]
