# Generated by Django 4.2.1 on 2024-02-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0011_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Categoria',
            new_name='categoriaId',
        ),
    ]
