# Generated by Django 4.2.1 on 2024-02-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0012_rename_categoria_produto_categoriaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
